version: "2"
services:
  app:
    image: gotoola/julspelet
    restart: always
    ports:
      - "80:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - DOCKER=true
      - ROUND_TIME_MS=300000
      - OPEN_SIGNAL_API_KEY=
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
